flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flaskblog.models import Post, User
from flask_login import current_user, login_required

main = Blueprint('main', __name__)




@main.route("/layout")
def layout():
    users = User.query.all()
    posts = Post.query.all()
    user = current_user
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("layout.html", posts=posts, title='Home', users=users, image_file=image_file, user=user)


@main.route("/")
@main.route("/home")
def home():
    users = User.query.all()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts, title='Home', users=users)


@main.route("/about")
@login_required
def about():
    users = User.query.all()
    posts = Post.query.all()
    return render_template("about.html", posts=posts, title='About Us', users=users)


@main.route("/versions")
@login_required
def versions():
    users = User.query.all()
    posts = Post.query.all()
    return render_template("versions.html", posts=posts, title='Versions', users=users)


@main.route("/trending")
@login_required
def trending():
    users = User.query.all()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("trending.html", title='Trending', posts=posts, users=users, image_file=image_file)

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, User
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    users = User.query.all()
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    posts = Post.query.all()
    return render_template("create_post.html", posts=posts, title='New Post', users=users, image_file=image_file, form=form, legend='New Post')



@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    users = User.query.all()
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("post.html", title=post.title, post=post, users=users, image_file=image_file)  

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    users = User.query.all()
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data 
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("create_post.html", title='Update Post', post=post, image_file=image_file, form=form, users=users, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    users = User.query.all()
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)



@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Welcome to Blogitpoints, home of positivity', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))

        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    users = User.query.all()
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, users=users)


@users.route("/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    users = User.query.all()
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user, users=users)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="mt-5">About</h1>
    <a href="https://www.facebook.com/blogitpoints/" style="color: white; text-decoration: none;" class="fab fa-facebook"></a>
    <a href="https://twitter.com/blogitpoints" style="color: white; text-decoration: none;" class="fab fa-twitter"></a>
    <a href="https://www.youtube.com/channel/UCbFlGVmVK0BeVM6dvFXkAJw" style="color: white; text-decoration: none;" class="fab fa-youtube"></a>
    <a href="https://www.instagram.com/blogitpoints/" style="color: white; text-decoration: none;" class="fab fa-instagram"></a>
    <a href="https://www.reddit.com/user/blogitpoints" style="color: white; text-decoration: none;" class="fab fa-reddit"></a>


    <div class="row mt-5 ml-1" style="max-width: 90vw; margin: auto;">
        <div class="card mb-5">
            <h2 class="card-header">Josh Ternyak</h2>
            <div class="card-body">
                <h4 class="card-title font-weight-light">Founder & Ceo of Blogitpoints</h4>
                <p class="card-text" style="max-width: 33rem;">I am Josh Ternyak, a web developer, designer, and founder of Blogitpoints.</p>
                <a href="mailto:joshtcodes@gmail.com" class="btn btn-primary">Contact</a>
                <a class="btn btn-outline-info ml-1" href="https://joshternyak.com">Portfolio</a>
            </div>
        </div>
    </div>
{% endblock %}

flaskblog/templates/account.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section mt-5">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>
{% endblock %}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}
  {% if current_user.is_authenticated %}
    {% else %}
    <div class="container pt-5" style="margin-top: 125px;">
      <h1 class="display-3 font-weight-bold">Blogitpoints</h1>
      <p class="lead" style="font-size: 25px;">Blogitpoints is a free social media platform all about sharing your stories with the world, and getting rewarded for being positive.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg big-button" href="{{ url_for('users.register') }}" role="button">Sign Up</a>
      </p>
    </div>
  {% endif %}
  {% if current_user.is_authenticated %}
  <h1 class="mt-5">Home</h1>
  <hr>
  {% for post in posts.items %}
      <article class="media content-section mt-5">
        <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="rounded-circle article-img">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
  {% endif %}
{% endblock %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="../static/img/bipfavicon.ico" type="image/x-icon">
    <link rel="icon" href="../static/img/bipfavicon.ico" type="image/x-icon">
    <script src="https://kit.fontawesome.com/6b1da2540e.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='messages.css') }}">
    {% if title %}
    <title>Blogitpoints - {{ title }}</title>
    {% else %}
    <title>Blogitpoints</title>
    {% endif %}
</head>
<body>
    <header style="z-index: 100;" class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4 logo" href="{{ url_for('main.home') }}">blogitpoints</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto"></div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <div class="dropdown mr-1">
                    <button type="button" class="btn btn-primary-outline bg-black dropdown-toggle text-white" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="0,20">
                    {{ current_user.username }}
                    </button>
                    <div class="dropdown-menu mt-2 pb-0" aria-labelledby="dropdownMenuOffset">
                      <a class="dropdown-item" title="Home" href="{{ url_for('main.home') }}">Home</a>
                      <a class="dropdown-item" title="Account" href="{{ url_for('users.account') }}">Account</a>
                      <a class="dropdown-item" title="New Post" href="{{ url_for('posts.new_post') }}">New Post</a>
                      <a class="dropdown-item" title="Trending" href="{{ url_for('main.trending') }}">Trending</a>
                      <a class="dropdown-item" title="Versions" href="{{ url_for('main.versions') }}">Versions</a>
                      <a class="dropdown-item" title="About" href="{{ url_for('main.about') }}">About</a>
                      <a class="dropdown-item bg-danger text-white" title="Logout" href="{{ url_for('users.logout') }}">Logout</a>
                    </div>
                  </div>
              {% else %}
              <!-- NOTHING -->
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    
    <main role="main" class="container mt-5">
      <div class="row mt-5">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
        </div>
        {% if current_user.is_authenticated %}
        <div class="col-md-4 mt-5">
            <div class="content-section p-4">
              <h3>Find Friends</h3>
              <p class='text-muted'>Here are all the people that use blogitpoints</p>
              {% for user in users %}
              <ul class="list-group mt-3">
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('users.user_posts', username=user.username) }}" class="text-dark">{{ user.username }}</a></li>
              </ul>
              {% endfor %}
            </div>
        </div>
        {% endif %}
        
      </div>
      
    </main>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script><script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section mt-5">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}

{% block content %}
    <article class="media content-section mt-4">
        <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="rounded-circle article-img">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ post.title }}</h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section mt-5">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/trending.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="mt-5">Trending</h1>
    <hr>
    <!-- Page Content -->
    {% for post in posts.items %}
        <article class="media content-section mt-3">
            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="rounded-circle article-img">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
    <div class="card mt-5 p-4">
        <img src="rounded-circle article-img" alt="">
        <h1 class="font-weight-bold">{{ user.username }}</h1>
        <h3>Posts: {{ posts.total }}</h3>
    </div>
    

    {% for post in posts.items %}
        <article class="media content-section mt-5">
          <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="rounded-circle article-img">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock %}

flaskblog/templates/versions.html
{% extends "layout.html" %}

{% block content %}

<section class="pricing mt-5">
    <div class="container">
      <div class="row">
        <!-- Free Tier -->
        <div class="col-lg-6">
          <div class="card mb-5 mb-lg-0">
            <div class="card-body">
              <h5 class="card-title text-muted text-uppercase text-center">Basic</h5>
              <h6 class="card-price text-center font-weight-bold">Free</h6>
              <hr>
              <ul class="fa-ul">
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Posting</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Daily Motivation</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Points</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Messaging</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Messaging Games</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Clicker Games</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Jobs</li>
                <li class="text-muted"><span class="fa-li"><i class="fas fa-times" style="color: red;"></i></span>Task Manager</li>
              </ul>
              <a href="{{ url_for('users.register') }}" class="btn btn-block btn-primary text-uppercase">Go There</a>
            </div>
          </div>
        </div>
        <!-- Plus Tier -->
        <div class="col-lg-6">
          <div class="card mb-5 mb-lg-0">
            <div class="card-body">
              <h5 class="card-title text-muted text-uppercase text-center">Premium</h5>
              <h6 class="card-price text-center font-weight-bold">$5<span class="period">/month</span></h6>
              <hr>
              <ul class="fa-ul">
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Posting</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Daily Motivation</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Points</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Messaging</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Messaging Games</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Clicker Games</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Jobs</li>
                <li><span class="fa-li"><i class="fas fa-check" style="color: green;"></i></span>Task Manager</li>
              </ul>
              <a href="#" class="btn btn-block btn-primary text-uppercase">Coming Soon</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}